#############################################################################
# Makefile for building: agave
# Generated by qmake (3.1) (Qt 5.12.8)
# Project:  agave.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile agave.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtOpenGL -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = agave1.0.0
DISTDIR = /home/rflores/p2026/p2026-2/Agave/Agave-1/src/.tmp/agave1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -lGLU -llapacke -llapack /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so /usr/lib/x86_64-linux-gnu/libGL.so -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Agave.cpp \
		Atom.cpp \
		Array.cpp \
		Basis.cpp \
		Curve.cpp \
		Element.cpp \
		Evaluator.cpp \
		GAPP.cpp \
		Grid.cpp \
		Integrator.cpp \
		Math.cpp \
		Matrix.cpp \
		Model.cpp \
		main.cpp \
		Plotter.cpp \
		QM.cpp \
		SCF.cpp \
		Set.cpp \
		Shell.cpp \
		Species.cpp \
		Structure.cpp \
		Surface.cpp \
		System.cpp \
		Units.cpp \
		Vector.cpp \
		Viewer.cpp \
		WinElement.cpp \
		WinGeo.cpp \
		WinPlot.cpp \
		WinProp.cpp \
		WinQM.cpp \
		WinSCF.cpp \
		WinSpecies.cpp moc_Agave.cpp \
		moc_Curve.cpp \
		moc_Plotter.cpp \
		moc_Viewer.cpp \
		moc_WinElement.cpp \
		moc_WinGeo.cpp \
		moc_WinPlot.cpp \
		moc_WinProp.cpp \
		moc_WinQM.cpp \
		moc_WinSCF.cpp \
		moc_WinSpecies.cpp
OBJECTS       = Agave.o \
		Atom.o \
		Array.o \
		Basis.o \
		Curve.o \
		Element.o \
		Evaluator.o \
		GAPP.o \
		Grid.o \
		Integrator.o \
		Math.o \
		Matrix.o \
		Model.o \
		main.o \
		Plotter.o \
		QM.o \
		SCF.o \
		Set.o \
		Shell.o \
		Species.o \
		Structure.o \
		Surface.o \
		System.o \
		Units.o \
		Vector.o \
		Viewer.o \
		WinElement.o \
		WinGeo.o \
		WinPlot.o \
		WinProp.o \
		WinQM.o \
		WinSCF.o \
		WinSpecies.o \
		moc_Agave.o \
		moc_Curve.o \
		moc_Plotter.o \
		moc_Viewer.o \
		moc_WinElement.o \
		moc_WinGeo.o \
		moc_WinPlot.o \
		moc_WinProp.o \
		moc_WinQM.o \
		moc_WinSCF.o \
		moc_WinSpecies.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		agave.pro Agave.h \
		Atom.h \
		Array.h \
		Basis.h \
		Curve.h \
		Element.h \
		Evaluator.h \
		GAPP.h \
		Global.h \
		Grid.h \
		Integrator.h \
		Math.h \
		Matrix.h \
		Model.h \
		Parameter.h \
		Plotter.h \
		QM.h \
		SCF.h \
		Set.h \
		Shell.h \
		Species.h \
		Structure.h \
		Surface.h \
		System.h \
		Units.h \
		Vector.h \
		Viewer.h \
		WinElement.h \
		WinGeo.h \
		WinPlot.h \
		WinProp.h \
		WinQM.h \
		WinSCF.h \
		WinSpecies.h Agave.cpp \
		Atom.cpp \
		Array.cpp \
		Basis.cpp \
		Curve.cpp \
		Element.cpp \
		Evaluator.cpp \
		GAPP.cpp \
		Grid.cpp \
		Integrator.cpp \
		Math.cpp \
		Matrix.cpp \
		Model.cpp \
		main.cpp \
		Plotter.cpp \
		QM.cpp \
		SCF.cpp \
		Set.cpp \
		Shell.cpp \
		Species.cpp \
		Structure.cpp \
		Surface.cpp \
		System.cpp \
		Units.cpp \
		Vector.cpp \
		Viewer.cpp \
		WinElement.cpp \
		WinGeo.cpp \
		WinPlot.cpp \
		WinProp.cpp \
		WinQM.cpp \
		WinSCF.cpp \
		WinSpecies.cpp
QMAKE_TARGET  = agave
DESTDIR       = 
TARGET        = agave


first: all
####### Build rules

agave:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: agave.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		agave.pro
	$(QMAKE) -o Makefile agave.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
agave.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile agave.pro

qmake_all: FORCE


all: Makefile agave

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents Agave.h Atom.h Array.h Basis.h Curve.h Element.h Evaluator.h GAPP.h Global.h Grid.h Integrator.h Math.h Matrix.h Model.h Parameter.h Plotter.h QM.h SCF.h Set.h Shell.h Species.h Structure.h Surface.h System.h Units.h Vector.h Viewer.h WinElement.h WinGeo.h WinPlot.h WinProp.h WinQM.h WinSCF.h WinSpecies.h $(DISTDIR)/
	$(COPY_FILE) --parents Agave.cpp Atom.cpp Array.cpp Basis.cpp Curve.cpp Element.cpp Evaluator.cpp GAPP.cpp Grid.cpp Integrator.cpp Math.cpp Matrix.cpp Model.cpp main.cpp Plotter.cpp QM.cpp SCF.cpp Set.cpp Shell.cpp Species.cpp Structure.cpp Surface.cpp System.cpp Units.cpp Vector.cpp Viewer.cpp WinElement.cpp WinGeo.cpp WinPlot.cpp WinProp.cpp WinQM.cpp WinSCF.cpp WinSpecies.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -W -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_Agave.cpp moc_Curve.cpp moc_Plotter.cpp moc_Viewer.cpp moc_WinElement.cpp moc_WinGeo.cpp moc_WinPlot.cpp moc_WinProp.cpp moc_WinQM.cpp moc_WinSCF.cpp moc_WinSpecies.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_Agave.cpp moc_Curve.cpp moc_Plotter.cpp moc_Viewer.cpp moc_WinElement.cpp moc_WinGeo.cpp moc_WinPlot.cpp moc_WinProp.cpp moc_WinQM.cpp moc_WinSCF.cpp moc_WinSpecies.cpp
moc_Agave.cpp: Agave.h \
		Parameter.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rflores/p2026/p2026-2/Agave/Agave-1/src/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rflores/p2026/p2026-2/Agave/Agave-1/src -I/home/rflores/p2026/p2026-2/Agave/Agave-1/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Agave.h -o moc_Agave.cpp

moc_Curve.cpp: Curve.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rflores/p2026/p2026-2/Agave/Agave-1/src/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rflores/p2026/p2026-2/Agave/Agave-1/src -I/home/rflores/p2026/p2026-2/Agave/Agave-1/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Curve.h -o moc_Curve.cpp

moc_Plotter.cpp: Plotter.h \
		Vector.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rflores/p2026/p2026-2/Agave/Agave-1/src/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rflores/p2026/p2026-2/Agave/Agave-1/src -I/home/rflores/p2026/p2026-2/Agave/Agave-1/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Plotter.h -o moc_Plotter.cpp

moc_Viewer.cpp: Viewer.h \
		Vector.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rflores/p2026/p2026-2/Agave/Agave-1/src/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rflores/p2026/p2026-2/Agave/Agave-1/src -I/home/rflores/p2026/p2026-2/Agave/Agave-1/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Viewer.h -o moc_Viewer.cpp

moc_WinElement.cpp: WinElement.h \
		Parameter.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rflores/p2026/p2026-2/Agave/Agave-1/src/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rflores/p2026/p2026-2/Agave/Agave-1/src -I/home/rflores/p2026/p2026-2/Agave/Agave-1/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include WinElement.h -o moc_WinElement.cpp

moc_WinGeo.cpp: WinGeo.h \
		Parameter.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rflores/p2026/p2026-2/Agave/Agave-1/src/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rflores/p2026/p2026-2/Agave/Agave-1/src -I/home/rflores/p2026/p2026-2/Agave/Agave-1/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include WinGeo.h -o moc_WinGeo.cpp

moc_WinPlot.cpp: WinPlot.h \
		Vector.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rflores/p2026/p2026-2/Agave/Agave-1/src/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rflores/p2026/p2026-2/Agave/Agave-1/src -I/home/rflores/p2026/p2026-2/Agave/Agave-1/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include WinPlot.h -o moc_WinPlot.cpp

moc_WinProp.cpp: WinProp.h \
		Parameter.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rflores/p2026/p2026-2/Agave/Agave-1/src/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rflores/p2026/p2026-2/Agave/Agave-1/src -I/home/rflores/p2026/p2026-2/Agave/Agave-1/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include WinProp.h -o moc_WinProp.cpp

moc_WinQM.cpp: WinQM.h \
		Parameter.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rflores/p2026/p2026-2/Agave/Agave-1/src/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rflores/p2026/p2026-2/Agave/Agave-1/src -I/home/rflores/p2026/p2026-2/Agave/Agave-1/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include WinQM.h -o moc_WinQM.cpp

moc_WinSCF.cpp: WinSCF.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rflores/p2026/p2026-2/Agave/Agave-1/src/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rflores/p2026/p2026-2/Agave/Agave-1/src -I/home/rflores/p2026/p2026-2/Agave/Agave-1/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include WinSCF.h -o moc_WinSCF.cpp

moc_WinSpecies.cpp: WinSpecies.h \
		Parameter.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rflores/p2026/p2026-2/Agave/Agave-1/src/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rflores/p2026/p2026-2/Agave/Agave-1/src -I/home/rflores/p2026/p2026-2/Agave/Agave-1/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include WinSpecies.h -o moc_WinSpecies.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

Agave.o: Agave.cpp Model.h \
		System.h \
		Parameter.h \
		QM.h \
		Matrix.h \
		Agave.h \
		Viewer.h \
		Vector.h \
		WinGeo.h \
		WinPlot.h \
		WinQM.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Agave.o Agave.cpp

Atom.o: Atom.cpp Atom.h \
		Parameter.h \
		Vector.h \
		Element.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Atom.o Atom.cpp

Array.o: Array.cpp Array.h \
		Matrix.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Array.o Array.cpp

Basis.o: Basis.cpp Atom.h \
		Parameter.h \
		Vector.h \
		Basis.h \
		Element.h \
		Global.h \
		Set.h \
		Structure.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Basis.o Basis.cpp

Curve.o: Curve.cpp Curve.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Curve.o Curve.cpp

Element.o: Element.cpp Element.h \
		Parameter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Element.o Element.cpp

Evaluator.o: Evaluator.cpp Atom.h \
		Parameter.h \
		Vector.h \
		Basis.h \
		Evaluator.h \
		Global.h \
		Integrator.h \
		Math.h \
		Matrix.h \
		System.h \
		Structure.h \
		Species.h \
		Set.h \
		Shell.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Evaluator.o Evaluator.cpp

GAPP.o: GAPP.cpp Array.h \
		Basis.h \
		GAPP.h \
		Matrix.h \
		Parameter.h \
		Global.h \
		Math.h \
		Species.h \
		System.h \
		Units.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GAPP.o GAPP.cpp

Grid.o: Grid.cpp Grid.h \
		Vector.h \
		Matrix.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Grid.o Grid.cpp

Integrator.o: Integrator.cpp Global.h \
		Integrator.h \
		Parameter.h \
		Shell.h \
		Set.h \
		Math.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Integrator.o Integrator.cpp

Math.o: Math.cpp Math.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Math.o Math.cpp

Matrix.o: Matrix.cpp Matrix.h \
		Math.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Matrix.o Matrix.cpp

Model.o: Model.cpp Atom.h \
		Parameter.h \
		Vector.h \
		Element.h \
		Model.h \
		Agave.h \
		Structure.h \
		System.h \
		Viewer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Model.o Model.cpp

main.o: main.cpp System.h \
		Agave.h \
		Parameter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

Plotter.o: Plotter.cpp Parameter.h \
		Global.h \
		Plotter.h \
		Vector.h \
		Viewer.h \
		Agave.h \
		Grid.h \
		Matrix.h \
		Species.h \
		Surface.h \
		System.h \
		Math.h \
		Units.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Plotter.o Plotter.cpp

QM.o: QM.cpp Global.h \
		QM.h \
		Parameter.h \
		Matrix.h \
		SCF.h \
		Species.h \
		System.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QM.o QM.cpp

SCF.o: SCF.cpp Math.h \
		QM.h \
		Parameter.h \
		Matrix.h \
		SCF.h \
		Species.h \
		Structure.h \
		Vector.h \
		System.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SCF.o SCF.cpp

Set.o: Set.cpp Parameter.h \
		Math.h \
		Set.h \
		Shell.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Set.o Set.cpp

Shell.o: Shell.cpp Global.h \
		Math.h \
		Parameter.h \
		Shell.h \
		Vector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Shell.o Shell.cpp

Species.o: Species.cpp Atom.h \
		Parameter.h \
		Vector.h \
		Basis.h \
		Global.h \
		Integrator.h \
		Math.h \
		Matrix.h \
		Set.h \
		Shell.h \
		Species.h \
		Structure.h \
		System.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Species.o Species.cpp

Structure.o: Structure.cpp Atom.h \
		Parameter.h \
		Vector.h \
		Structure.h \
		Units.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Structure.o Structure.cpp

Surface.o: Surface.cpp Agave.h \
		Parameter.h \
		Atom.h \
		Vector.h \
		Basis.h \
		Evaluator.h \
		Global.h \
		Grid.h \
		Matrix.h \
		Surface.h \
		System.h \
		Species.h \
		Structure.h \
		Set.h \
		Shell.h \
		Plotter.h \
		Math.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Surface.o Surface.cpp

System.o: System.cpp Global.h \
		Integrator.h \
		Parameter.h \
		Species.h \
		Structure.h \
		Vector.h \
		System.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o System.o System.cpp

Units.o: Units.cpp Math.h \
		Units.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Units.o Units.cpp

Vector.o: Vector.cpp Global.h \
		Math.h \
		Matrix.h \
		Vector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Vector.o Vector.cpp

Viewer.o: Viewer.cpp Atom.h \
		Parameter.h \
		Vector.h \
		Element.h \
		Model.h \
		Plotter.h \
		Agave.h \
		Structure.h \
		System.h \
		Units.h \
		Viewer.h \
		WinGeo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Viewer.o Viewer.cpp

WinElement.o: WinElement.cpp Element.h \
		Parameter.h \
		WinElement.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o WinElement.o WinElement.cpp

WinGeo.o: WinGeo.cpp Atom.h \
		Parameter.h \
		Vector.h \
		Element.h \
		Agave.h \
		Structure.h \
		System.h \
		Units.h \
		Viewer.h \
		WinElement.h \
		WinGeo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o WinGeo.o WinGeo.cpp

WinPlot.o: WinPlot.cpp Global.h \
		Grid.h \
		Vector.h \
		Matrix.h \
		Parameter.h \
		Plotter.h \
		Agave.h \
		Surface.h \
		System.h \
		Viewer.h \
		WinPlot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o WinPlot.o WinPlot.cpp

WinProp.o: WinProp.cpp GAPP.h \
		Matrix.h \
		Parameter.h \
		Global.h \
		QM.h \
		Units.h \
		WinProp.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o WinProp.o WinProp.cpp

WinQM.o: WinQM.cpp Global.h \
		QM.h \
		Parameter.h \
		Matrix.h \
		Agave.h \
		System.h \
		WinProp.h \
		WinQM.h \
		WinSCF.h \
		WinSpecies.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o WinQM.o WinQM.cpp

WinSCF.o: WinSCF.cpp Curve.h \
		Math.h \
		Parameter.h \
		QM.h \
		Matrix.h \
		Agave.h \
		SCF.h \
		Structure.h \
		Vector.h \
		System.h \
		Viewer.h \
		WinSCF.h \
		WinPlot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o WinSCF.o WinSCF.cpp

WinSpecies.o: WinSpecies.cpp Global.h \
		QM.h \
		Parameter.h \
		Matrix.h \
		Structure.h \
		Vector.h \
		System.h \
		WinSpecies.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o WinSpecies.o WinSpecies.cpp

moc_Agave.o: moc_Agave.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Agave.o moc_Agave.cpp

moc_Curve.o: moc_Curve.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Curve.o moc_Curve.cpp

moc_Plotter.o: moc_Plotter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Plotter.o moc_Plotter.cpp

moc_Viewer.o: moc_Viewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Viewer.o moc_Viewer.cpp

moc_WinElement.o: moc_WinElement.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_WinElement.o moc_WinElement.cpp

moc_WinGeo.o: moc_WinGeo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_WinGeo.o moc_WinGeo.cpp

moc_WinPlot.o: moc_WinPlot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_WinPlot.o moc_WinPlot.cpp

moc_WinProp.o: moc_WinProp.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_WinProp.o moc_WinProp.cpp

moc_WinQM.o: moc_WinQM.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_WinQM.o moc_WinQM.cpp

moc_WinSCF.o: moc_WinSCF.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_WinSCF.o moc_WinSCF.cpp

moc_WinSpecies.o: moc_WinSpecies.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_WinSpecies.o moc_WinSpecies.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

